global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'admin-prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '127.0.0.1:18083' ]

#
#  - job_name: 'otel-collector'
#    scrape_interval: 2s
#    static_configs:
#      - targets: ['otel-collector:8888']
